Support LinkedIn Version 2 API
wso2-extensions/identity-outbound-auth-linkedIn pull request #13
Opened 2019-04-04 19:59 UTC by robsonkades

## Purpose
> LinkedIn has published this update last December:
https://engineering.linkedin.com/blog/2018/12/developer-program-updates
According to the document, the v1 API will cease to function as of March 1, 2019.

## Goals
> Added support for authentication, token and claims of the new linkedIn Api version;

- [x] Apps with old version api.
- [x] Apps with new version api.

## User stories
> After March 1, 2019, Apps created in Linkedin no longer work in the current version of dropin, because the app uses version 2 of the api.

## Release note
> Due to disapproved fields in LinkedIn, only the emailAddress, firstName, lastName and id claims are available

## Documentation
> https://docs.wso2.com/display/ISCONNECTORS/Configuring+LinkedIn+Authenticator

2019-06-01 17:20 UTC, morganm00 requested changes
Tested and worked except for the LinkedIn ID was not returned.    Recommend changing in LinkedInAuthenticatorConstants:
LINKEDIN_USERINFO_ENDPOINT = "https://api.linkedin.com/v2/me?projection=(firstName,lastName)"
to
LINKEDIN_USERINFO_ENDPOINT = "https://api.linkedin.com/v2/me?projection=(firstName,lastName,id)"

When I did that everything worked as in version 1.

2019-06-01 17:23 UTC, robsonkades commented
@morganm00 https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/pull/13/commits/efe09de051c8885529e42e527fbf3cbbe9c0a7ef

2019-06-01 17:45 UTC, morganm00 approved these changes
Works now.   Thanks.

2019-08-06 06:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2-extensions/identity-outbound-auth-linkedIn?pullRequest=13) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2-extensions/identity-outbound-auth-linkedIn?pullRequest=13) before we can accept your contribution.<br/><hr/>**Robson Kades** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2-extensions/identity-outbound-auth-linkedIn?pullRequest=13) it.</sub>

2020-01-08 04:36 UTC, madurangasiriwardena commented
Hi @robsonkades, Thank you for your valuable contributions and extremely sorry for the delay in getting back to you.
This functionality is already implemented with this [pull request](https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/pull/15). Hence we are closing this.

2020-01-08 04:36 UTC, closed without merging